### ISSUE TITLE
Adding (automatically) hidden courses to current semester

### ISSUE THREAD

**Issue by YconquestY** [AENeuro/HKU-Moodle-Helper#3]
Good evening.

ITS upgraded [HKU Moodle](https://moodle.hku.hk) this summer such that **not all** courses are listed on the landing page. One may view her/his enrollment history via [`My courses`](https://moodle.hku.hk/my/) at the bottom of the page.

This poses challenges to the current version of our plugin. It **no longer works** in that an in-progress course is missing from the list as long as it is hidden. Below is an example where COMP3361 has been registered, but it does not appear on the landing page.

| Add COMP3361 to the current semester via search | COMP3361 does not appear on the landing page. |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/60956084/187659520-5e7390e0-c843-41d0-a9bc-145aab8fe3f0.png"> | <img src="https://user-images.githubusercontent.com/60956084/187660031-20c73dfe-8318-4f25-a93d-80bee141eb56.png"> |

Despite my will to help, I am not familiar with front-end stuff. Can you fix this issue?

**Comment by AENeuro** [comment]
Thanks for bringing up this issue. Can I confirm with you that even if said course **has been enrolled (and approved)**, the respective course moodle does not appear on the landing page? That effectively means one must search with the course code every time they wish to enter the module.

To make sure we're on the same page, I am aware that not all **enrolled** courses appear on the landing page at once. There are instances where certain module doesn't pop up until the end of ADP, or not at all throughout the semester (I assume that's because the lecturer does not have anything to post). Is this what we're discussing here?

**Comment by YconquestY** [comment]
> Can I confirm with you that even if said course **has been enrolled (and approved)**, the respective course moodle does not appear on the landing page?

That's right.

> There are instances where certain module doesn't pop up until the end of ADP, or not at all throughout the semester (I assume that's because the lecturer does not have anything to post).

Those courses are hidden or, from my perspective, folded. Not only are (more than half) currently registered classes gone, at least $10$ previously enrolled courses are not on the landing page. I may access all courses via (1) the `My courses` sidebar on the left or (2) the search box at the bottom.

<img width="1280" alt="1662366661941" src="https://user-images.githubusercontent.com/60956084/188404934-e3bb7efb-b36b-4c17-972d-2a08f12c7dff.png">

**Comment by AENeuro** [comment]
Thanks for the helpful details again, Will. 

> Those courses are hidden or, from my perspective, folded... (more than half) currently registered classes gone

What it sounds like is major oversight on ITS's part. Can't fathom what could possibly be the reason for ITS to fold currently enrolled courses on the home page. 

It's a bigger issue than I had originally perceived. I'll look into it these couple of days, and try to figure out what it means for this plugin.

**Comment by AENeuro** [comment]
A new version will be out soon allowing users to add course from the search page and the sidebar.
Thanks again for flagging.
