### ISSUE TITLE
Cannot use HKUMoodle Helper in new HKU Moodle

### ISSUE THREAD

**Issue by linearalgebrayhz** [AENeuro/HKU-Moodle-Helper#6]
Hi! I noticed that the HKU Moodle was updated yesterday and the `Add to this semester` button on the course profile is no longer useful, while the button in the side column still works. Also, in my Explorer, these components do not display correctly. Please find the attached image for information. Thank you for your attention to this!

![1722256288033](https://github.com/user-attachments/assets/461310fb-a8e6-47a7-a658-f854d830892c)

**Comment by LeeHengYu** [comment]
@linearalgebrayhz I think it's even worse now, recently they removed the "My courses" section in the side column which destroyed the main pivot point of the extension. Now either this extension needs to revamp its implementation or this extension is of little use. I currently am working on another extension that reverts this side column section back.

**Comment by AENeuro** [comment]
Looping in active dev team @PeterZh6

**Comment by AENeuro** [comment]
Apologies for the delayed turnaround. A new patch #7  will be deployed to address this

**Comment by PeterZh6** [comment]
> Apologies for the delayed turnaround. A new patch #7 will be deployed to address this

[new version](https://chromewebstore.google.com/detail/hku-moodle-helper/einenigpmpgopefpkfbmnlcjmoamijap) released
