### ISSUE TITLE
still cannot use the helper

### ISSUE THREAD

**Issue by jackyshen0313** [AENeuro/HKU-Moodle-Helper#8]
the buttons are shown, but clicking them has no use

**Comment by AENeuro** [comment]
Hi there, thanks for raising. Kindly check if you're running 1.4.8 version of the extension (released two days ago).

If not: 
- consider reinstalling the extension to force an update
- or Wait a few days and it will automatically update itself to the latest
- or force an update by enabling developer mode and click "update"

The version number is available at chrome://extensions/
